---
# vars file for sample-role_nginx-ubuntu â€” role internals, higher precedence than defaults
nginx_conf_path: /etc/nginx/nginx.conf
nginx_sites_available: /etc/nginx/sites-available
nginx_sites_enabled: /etc/nginx/sites-enabled
