galaxy_info:
  author: Sayantan
  description: Install and configure nginx
  company: TEOCO Software
  license: MIT
  min_ansible_version: "2.13"
  platforms:
    - name: Ubuntu
      versions:
        - "bionic"
        - "focal"
        - "jammy"
dependencies: []